add variables and first profile
FbW36/1-PB-console pull request #11
Opened 2020-10-05 11:56 UTC by mizzrawr

pls check my super mega awesome code

2020-10-05 12:32 UTC, Ghassanooooo requested changes
Please create a folder with your name holds JavaScript file

2020-10-06 08:05 UTC, ciamac-da commented on index.js
> +
The content of console.log should be "this is an exercise in console logging" :))

2020-10-06 08:12 UTC, ciamac-da requested changes
Hola Cindy:) You forgot to make a folder! You have to make a folder and put your index.js inside of this folder! And there's also a tiny mistake about the first  task. The content of console.log should be "this is an exercise in console logging" :))

2020-10-06 08:40 UTC, mizzrawr commented on index.js
> +
``console.log("This is an exercise in console logging");

2020-10-07 06:13 UTC, merged